/**
 * Generates src/ai/preflop-table.ts: all-in equity of each of the 169 starting-hand classes
 * against one and against three random hands, by Monte Carlo with this project's own evaluator.
 * Deterministic (seeded), so regenerating produces the same file.
 *
 *   node scripts/gen-preflop-table.ts [samplesPerClass]
 */
import { writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { makeCard } from '../src/engine/cards.ts';
import { evaluate } from '../src/engine/evaluator.ts';
import { SeededRng, randomInt } from '../src/engine/rng.ts';
import { className } from '../src/ai/combos.ts';

const samples = Number(process.argv[2] ?? 60000);
const rng = new SeededRng('preflop-table-v1');

function representative(cls: number): [number, number] {
  const r1 = Math.floor(cls / 13);
  const r2 = cls % 13;
  if (r1 === r2) return [makeCard(r1, 3), makeCard(r1, 2)];
  if (r1 > r2) return [makeCard(r1, 3), makeCard(r2, 3)]; // suited
  return [makeCard(r2, 3), makeCard(r1, 2)]; // offsuit
}

function equity(hole: [number, number], opponents: number): number {
  const rest: number[] = [];
  for (let c = 0; c < 52; c++) if (c !== hole[0] && c !== hole[1]) rest.push(c);
  const cards = new Int32Array(7);
  let total = 0;
  for (let s = 0; s < samples; s++) {
    // Partial Fisher–Yates: 5 board cards + 2 per opponent.
    const need = 5 + 2 * opponents;
    for (let i = 0; i < need; i++) {
      const j = i + randomInt(rng, rest.length - i);
      const t = rest[i]!;
      rest[i] = rest[j]!;
      rest[j] = t;
    }
    for (let i = 0; i < 5; i++) cards[2 + i] = rest[i]!;
    cards[0] = hole[0];
    cards[1] = hole[1];
    const mine = evaluate(cards, 7);
    let best = -1;
    let ties = 0;
    for (let o = 0; o < opponents; o++) {
      cards[0] = rest[5 + 2 * o]!;
      cards[1] = rest[6 + 2 * o]!;
      const v = evaluate(cards, 7);
      if (v > best) {
        best = v;
        ties = 1;
      } else if (v === best) ties++;
    }
    if (mine > best) total += 1;
    else if (mine === best) total += 1 / (ties + 1);
  }
  return total / samples;
}

const hu: number[] = [];
const three: number[] = [];
for (let cls = 0; cls < 169; cls++) {
  const hole = representative(cls);
  hu.push(Number(equity(hole, 1).toFixed(4)));
  three.push(Number(equity(hole, 3).toFixed(4)));
}

const lines = [
  '// Generated by scripts/gen-preflop-table.ts — do not edit by hand.',
  `// ${samples} Monte Carlo samples per class and opponent count, seed "preflop-table-v1".`,
  '// Index = 13×13 class grid (see combos.ts): pairs r*13+r, suited hi*13+lo, offsuit lo*13+hi.',
  '',
  '/** All-in equity vs one random hand. */',
  `export const PREFLOP_EQUITY_HU: readonly number[] = [${hu.join(', ')}];`,
  '',
  '/** All-in equity vs three random hands. */',
  `export const PREFLOP_EQUITY_4WAY: readonly number[] = [${three.join(', ')}];`,
  '',
];
const out = fileURLToPath(new URL('../src/ai/preflop-table.ts', import.meta.url));
writeFileSync(out, lines.join('\n'));
const top = hu.map((e, i) => [className(i), e] as const).sort((a, b) => b[1] - a[1]);
console.log(`wrote ${out}`);
console.log('strongest:', top.slice(0, 6).map(([n, e]) => `${n} ${e}`).join(', '));
console.log('weakest:', top.slice(-4).map(([n, e]) => `${n} ${e}`).join(', '));
